"""Add date_posted to Post model

Revision ID: 834e94d73a01
Revises: e0c76b46ea57
Create Date: 2025-01-04 08:01:30.645953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834e94d73a01'
down_revision = 'e0c76b46ea57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
